project_name: kubectl-triage
release:
  github:
    owner: Lc-Lin
    name: kubectl-triage
builds:
  - id: kubectl-triage
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags:
      - -s -w
archives:
  - id: kubectl-triage
    builds:
    - kubectl-triage
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
